export const Users = [
  {
    id: 1,
    profilePicture: './images/1.jpg',
    username: 'Safak Kocaoglu',
  },
  {
    id: 2,
    profilePicture: './images/2.jpg',
    username: 'Janell Shrum',
  },
  {
    id: 3,
    profilePicture: './images/3.jpg',
    username: 'Alex Durden',
  },
  {
    id: 4,
    profilePicture: './images/4.jpg',
    username: 'Dora Hawks',
  },
  {
    id: 5,
    profilePicture: './images/5.jpg',
    username: 'Thomas Holden',
  },
  {
    id: 6,
    profilePicture: './images/6.jpg',
    username: 'Shirley Beauchamp',
  },
  {
    id: 7,
    profilePicture: './images/7.jpg',
    username: 'Travis Bennett',
  },
  {
    id: 8,
    profilePicture: './images/8.jpg',
    username: 'Kristen Thomas',
  },
  {
    id: 9,
    profilePicture: './images/chef.png',
    username: 'Gary Duty',
  },
];

export const Posts = [
  {
    id: 1,
    desc: 'Love For All, Hatred For None.',
    photo: './images/1.jpeg',
    date: '5 mins ago',
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: './images/findus.png',
    date: '15 mins ago',
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: 'Every moment is a fresh beginning.',
    photo: './images/gallery01.png',
    date: '1 hour ago',
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: './images/gallery02.png',
    date: '4 hours ago',
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: './images/gallery03.png',
    date: '5 hours ago',
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: './images/gallery04.png',
    date: '1 day ago',
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: 'Never regret anything that made you smile.',
    photo: './images/menu.png',
    date: '2 days ago',
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: './images/welcome.png',
    date: '3 days ago',
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: 'Change the world by being yourself.',
    photo: 'assets/post/9.jpeg',
    date: '5 days ago',
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: 'assets/post/10.jpeg',
    date: '1 week ago',
    userId: 10,
    like: 104,
    comment: 12,
  },
];
